### ISSUE TITLE
Allow definiting Status, enabled or disabled, in pool attachment

### ISSUE THREAD

**Issue by DavidGamba** [F5Networks/terraform-provider-bigip#114]
Currently, there is no way to manage pool member status through Terraform. 

I set the status to disabled when I am migrating nodes and want the connections to gracefully drain before removing them from the pool.

I am assuming the place to do this would be the pool attachment resource.

**Comment by earchibald-lv** [comment]
I tried setting `state = "user-down"` on the bigip_ltm_node to see if it would affect things.

If I **only** create the node without attaching it to a pool, the node is properly set to disabled.

However, if I specify the node and attach it to a pool, the node ignores the `state` parameter and is up (even though Terraform state shows `state` as `user-down`.)

**Comment by RavinderReddyF5** [comment]
@earchibald-lv 
we tried same scenario manually and observed below things.

when attaching any **ltm node** to  a **ltm pool**,  bigip will not consider current state of node.

we have to explicitly set node state as shown below snapshot.

![image](https://user-images.githubusercontent.com/45624469/70992491-d3bef080-20ef-11ea-836f-0bcf7cbaeac6.png)

![image](https://user-images.githubusercontent.com/45624469/70992639-23052100-20f0-11ea-96f3-021a6fefb97a.png)

we can add node_status attribute in "pool attachment resource"  which user can add explicitly based on the node status.

**Comment by rleonetti** [comment]
Is this being looked into at all? This type of lacking support makes it impossible to manage the F5 with a tool like Terraform beyond initial configuration.
When I choose 'user-up' or 'user-down' for the node, it either sets the node state to forced offline or disabled. Neither of them show the node as enabled.

Even if that worked, you can't only rely on this for gracefully draining connections since sometimes a node is part of multiple pools and disabling an entire node is not an option. Why is there no way to configure state through the pool membership?

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
