### ISSUE TITLE
Changing IP on bigip_ltm_node fails

### ISSUE THREAD

**Issue by ajchiarello** [F5Networks/terraform-provider-bigip#290]
In my terraform script, I am creating several bigip_ltm_node resources, and attaching them to a bigip_ltm_pool. Upon initial creation this works fine - but it throws an error if the IP address on one of my nodes changes. Terraform correctly sees the IP change, and moves to recreate the bigip_ltm_node resource, but the F5 throws an error because the node is a part of the pool.

Is there a way to have the pool_attachment always be destroyed/recreated when the node is? I know this may be a terraform problem and not a provider one. I've included the relevant code below, in case I'm missing something obvious.

> resource "bigip_ltm_pool" "control" {
>   name     = "/K8S/${var.project_name}-control-pool"
>   monitors = [ "/K8S/https_6443" ]
> }
> 
> resource "bigip_ltm_pool_attachment" "control" {
>   for_each   = local.rancher_node_map
>   pool       = bigip_ltm_pool.control.name
>   node       = "${bigip_ltm_node.control[each.key].name}:6443"
>   depends_on = [ bigip_ltm_node.control ]
> }
> 
> resource "bigip_ltm_node" "control" {
>   for_each = local.rancher_node_map
>   name     = "/K8S/${each.key}"
>   address  = each.value
>   monitor  = "/K8S/https_6443 and /Common/icmp "
> }

**Comment by focrensh** [comment]
Reviewing possibilities via TER-343

**Comment by papineni87** [comment]
@ajchiarello  we have added new behaviour to ltm_pool_attachment  resource where you can pass node details directly with ip:port/fqdn:port instead of node reference. With this approach we can change node ip in pool attachment itself, without any need of node resource. This will not have any dependencies on other resources, and let me if this works. This changes are in 1.4 release and documentation also updated with these changes
