### ISSUE TITLE
Feature Request:  Add capability to tolerate existing node

### ISSUE THREAD

**Issue by theseao** [F5Networks/terraform-provider-bigip#53]
Hello

Is it possible to add capability to the bigip_ltm_node resource to not error out (ignore) when encountering an existing node?   

Thanks

**Comment by dannyk81** [comment]
The general behavior in Terraform is that existing resource (created outside of Terraform) should be imported into the state, the error here is actually coming from F5 itself as the same resource you try to provision via Terraform already exists.

If you use `terraform import`, you can add that node to your state and terraform won't try to provision it again.

**Comment by dannyk81** [comment]
It would be easier to understand if you can share your terraform
configuration for the relevant bigip resources.

in general, this shouldn't happen - the nodes resource should be created
once and later referenced in all the relevant pools (virtual servers don't
reference nodes by the way)

**Comment by ddcrjlalumiere** [comment]
So, I'm running in to this issue as well. Basically, trying to setup a blue / green set of of environments so we can test changes on parallel configurations before cutovers. We've one set of Terraform code for blue and another set for green. Most of the resources have (blue|green) in their name to avoid duplication, but since we are using FQDN nodes those are named the same in both places and Terraform bails due to the existing resource from the other color. Is it possible for it to just go "oh, this resource exists and is exactly the same as what I want to create, so carry on"?

**Comment by KrithikaChidambaram** [comment]
Hi, closing this request now. 
Please re-open if required or send an email to [automation_ecosystem@f5.com](mailto:automation_ecosystem@f5.com). Thanks!
